exclude: ^\. # Exclude every file or folder starting with a dot.

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
        exclude: ^datasets/
        types: [text]
    -   id: end-of-file-fixer
        types: [text]
    -   id: requirements-txt-fixer 
        files: /requirements.*.txt$
    -   id: check-added-large-files
    -   id: check-case-conflict

-   repo: https://github.com/pycqa/isort
    rev: 5.11.4
    hooks:
    -   id: isort
        name: isort
        args:
        -   --filter-files
        -   --profile=black

-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    -   id: black
        files: ^project/
        types: [python]
        require_serial: true
    -   id: black-jupyter
        files: ^notebooks/
        types_or: [python, pyi, jupyter]
        require_serial: true
        additional_dependencies: [".[jupyter]"]

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        exclude: migrations/.*|^project/project/settings/
        additional_dependencies:
        -   flake8-black
        args: [
          '--max-line-length=88',
          '--ignore=E203,E402,E501,E800,W503',
          '--select=B,C,E,F,W,T4,B9'
        ]