# Generated by Django 4.1.4 on 2022-12-27 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datacore", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="relation",
            name="ontology_domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="datacore.domainontology",
            ),
        ),
        migrations.AlterField(
            model_name="relation",
            name="relation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VERB_GROUP", "belong to verb group of"),
                    ("CAUSES", "causes"),
                    ("ENTAILMENTS", "entails"),
                    ("IN_REGION_DOMAINS", "exists/happens in"),
                    ("ATTRIBUTES", "has the attribute"),
                    ("IN_TOPIC_DOMAINS", "in topic"),
                    ("HYPONYM", "is a kind of"),
                    ("MEMBER_HOLONYM", "is a member of"),
                    ("PART_HOLONYM", "is a part of"),
                    ("SUBSTANCE_HOLONYM", "is a substance of"),
                    ("HYPERNYM", "is a supertype of"),
                    ("INSTANCE_OF", "is an instance of"),
                    ("CAUSED", "is caused by"),
                    ("ALSO_SEES", "is related to"),
                    ("REGION_DOMAINS", "is relatet to region"),
                    ("SIMILAR_TOS", "is similar to"),
                    ("TOPIC_DOMAINS", "is under topic domain of"),
                    ("REGION_DOMAINS", "is used in"),
                    ("USAGE_DOMAINS", "linguistically is a"),
                    ("MANNER", "manner"),
                    ("MATERIAL", "material"),
                    ("NEG_BENEFICIARY", "negative beneficiary"),
                    ("PARTICIPANT", "participant"),
                    ("POS_BENEFICIARY", "positive beneficiary"),
                    ("SECONDARY_PARTICIPANT", "Secondary participant"),
                    ("STATE", "state"),
                    ("TOPIC_DOMAINS", "sub-topic"),
                    ("IN_USAGE_DOMAINS", "used in things like"),
                ],
                max_length=64,
                null=True,
            ),
        ),
    ]
