# Generated by Django 4.1.4 on 2022-12-30 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datacore", "0002_relation_ontology_domain_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="axiom",
            name="ontology_domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="datacore.domainontology",
            ),
        ),
        migrations.AddField(
            model_name="restriction",
            name="ontology_domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="datacore.domainontology",
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="ontology_domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="datacore.domainontology",
            ),
        ),
    ]
