INSTANCE = [
    ("ARTIFACT", "Artifacts"),
    ("CARDINAL", "Cardinal"),
    ("DATE", "Date"),
    ("DOCUMENT", "Documents"),
    ("EVENT", "Event"),
    ("FACILITY", "Facility"),
    ("GEOGRAPHICAL.LOCATION", "Geographical Location"),
    ("GPE", "Geopolitical Entity"),
    ("GROUP", "Group(nationality, religion,...)"),
    ("LANGUAGE", "Language"),
    ("LAW", "Law"),
    ("MONEY", "Money"),
    ("NAT", "Natural Phenomenon"),
    ("ORDINAL", "Ordinal"),
    ("ORGANIZATION", "Organization"),
    ("PERCENT", "Percentage"),
    ("PERSON", "Person"),
    ("PRODUCT", "Product"),
    ("QUANTITY", "Quantity"),
    ("TIME", "Time"),
    ("PRODUCT.VER", "Versioned Product"),
    ("WORK_OF_ART", "Work of art"),
]

MORPHEME = [
    ("MORPHEME", "Morpheme"),
    ("AFFIX", "Affix"),
    ("CIRCUMFIX", "Circumfix"),
    ("INFIX", "Infix"),
    ("PREFIX", "Prefix"),
    ("SUFFIX", "Suffix"),
    ("BOUND_MORPHEMES", "Bound morphemes"),
    ("FREE_MORPHEME", "Free Morpheme"),
]

POS = [
    ("ADJ", "adjective"),
    ("ADP", "adposition"),
    ("ADV", "adverb"),
    ("POS_AUX", "auxiliary"),
    ("CCONJ", "coordinating conjunction"),
    ("POS_DET", "determiner"),
    ("INTJ", "interjection"),
    ("NOUN", "noun"),
    ("NOUN.ADR", "Address"),
    ("NOUN.DAT", "Date"),
    ("NOUN.MAI", "Email address"),
    ("NOUN.HOU", "Hour"),
    ("NOUN.MEA", "Measure"),
    ("NOUN.MON", "Money"),
    ("NOUN.PCT", "Percentage"),
    ("NOUN.PHO", "Phone number"),
    ("NOUN.WEB", "Web address"),
    ("NUM", "numeral"),
    ("X", "other"),
    ("PARTICLE", "particle"),
    ("PRON", "pronoun"),
    ("PROPN", "proper noun"),
    ("PROPN.BLD", "A building"),
    ("PROPN.COM", "A business/company"),
    ("PROPN.DEV", "A device"),
    ("PROPN.DOC", "A document"),
    ("PROPN.FDD", "A food/beverage"),
    ("PROPN.NPH", "A human being"),
    ("PROPN.LEN", "A legal/fiscal entity"),
    ("PROPN.MMD", "A mass media"),
    ("PROPN.GEA", "A physical geographic feature"),
    ("PROPN.PRD", "A product"),
    ("PROPN.VCL", "A vehicle"),
    ("PROPN.WRK", "a work of human intelligence"),
    ("PROPN.GEO", "An administrative geographic area"),
    ("PROPN.ANM", "An animal"),
    ("PROPN.EVN", "An event"),
    ("PROPN.GEX", "An extra-terrestrial or imaginary place"),
    ("PROPN.PPH", "An physical phenomena"),
    ("PROPN.ORG", "organization/society/institution"),
    ("POS_PUNCT", "punctuation"),
    ("SCONJ", "subordinating conjunction"),
    ("SYM", "symbol"),
    ("VERB", "verb"),
]

PHRASE = [
    ("None", "declarative"),
    ("None", "exclamative"),
    ("None", "Expressed Condition"),
    ("None", "Imperative"),
    ("None", "Incomplete"),
    ("None", "Interrogative"),
    ("PROVERB", "Proverb"),
    ("EXPS", "Expression"),
    ("IDM", "Idiom"),
    ("PRVB", "Proveb"),
    ("SYNG", "Saying"),
    ("SLNG", "Slang"),
    ("REFERENCE", "Reference"),
]

WORD_COLLECTION = [
    ("NGRAM", "N-Gram"),
    ("POS_NGRAM", "Part Of Speech N-grams"),
    ("SEMANTIC_NGRAM", "Semantic n-gram"),
    ("SYNTATIC_NGRAM", "Syntactic n-grams"),
]

RELATION = [
    ("VERB_GROUP", "belong to verb group of"),
    ("CAUSES", "causes"),
    ("ENTAILMENTS", "entails"),
    ("IN_REGION_DOMAINS", "exists/happens in"),
    ("ATTRIBUTES", "has the attribute"),
    ("IN_TOPIC_DOMAINS", "in topic"),
    ("HYPONYM", "is a kind of"),
    ("MEMBER_HOLONYM", "is a member of"),
    ("PART_HOLONYM", "is a part of"),
    ("SUBSTANCE_HOLONYM", "is a substance of"),
    ("HYPERNYM", "is a supertype of"),
    ("INSTANCE_OF", "is an instance of"),
    ("CAUSED", "is caused by"),
    ("ALSO_SEES", "is related to"),
    ("REGION_DOMAINS", "is relatet to region"),
    ("SIMILAR_TOS", "is similar to"),
    ("TOPIC_DOMAINS", "is under topic domain of"),
    ("REGION_DOMAINS", "is used in"),
    ("USAGE_DOMAINS", "linguistically is a"),
    ("MANNER", "manner"),
    ("MATERIAL", "material"),
    ("NEG_BENEFICIARY", "negative beneficiary"),
    ("PARTICIPANT", "participant"),
    ("POS_BENEFICIARY", "positive beneficiary"),
    ("SECONDARY_PARTICIPANT", "Secondary participant"),
    ("STATE", "state"),
    ("TOPIC_DOMAINS", "sub-topic"),
    ("IN_USAGE_DOMAINS", "used in things like"),
]
